networks:
  metrics:
    name: metrics
    driver: bridge

services:

  nodeexporter:
    image: prom/node-exporter:latest
    restart: always 
    networks:
      - metrics
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/host/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--path.rootfs=/host/rootfs'

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    restart: always
    volumes:
      - /:/rootfs:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk/:ro
    privileged: true
    command:
      - "--enable_metrics=cpu,memory,network"
      - "--store_container_labels=false"
      - "--docker_only=true"
    networks:
      - metrics
